version: '3'

services:

    api:
     container_name: api-company-dock
     restart: always
     build: .
     ports:
      - 4000:1234

     links:
      - postgres
      
    postgres:
        image: postgres
        environment: 
          - DATABASE_HOST=localhost     
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=12345
          - POSTGRES_DB=openhostel
        ports: 
          - 5432:5432
    pgadmin:
        image: dpage/pgadmin4
        environment: 
          PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
          PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
          - "5050:80"
        depends_on: 
          - postgres